### ISSUE TITLE
OSError: Not found: unknown field name "mining_sentence_size" in TrainerSpec.

### ISSUE THREAD

**Issue by nbutyrate** [ehsanasgari/DiTaxa#1]
Hi I was trying to run your test

here is the error

sentencepiece_trainer.cc(116) LOG(INFO) Running command: --input=tmp/tmp_txt --model_prefix=results_dental/intermediate_files/npe_segmentatation/periodontal_unique_50000_v_5000_s --add_dummy_prefix=0 --max_sentencepiece_length=512 --model_type=bpe --mining_sentence_size=5000000 --input_sentence_size=10000000 --vocab_size=50000
Traceback (most recent call last):
  File "ditaxa.py", line 160, in <module>
    err = checkArgs(sys.argv)
  File "ditaxa.py", line 131, in checkArgs
    Pipeline.train_npe()
  File "/Users/sangwan/Desktop/Softwares/DiTaxa-master/main/DiTaxa.py", line 87, in train_npe
    backend='Sentencepiece',num_p=self.num_p)
  File "/Users/sangwan/Desktop/Softwares/DiTaxa-master/make_representations/npe_segmentation_train.py", line 63, in generate
    '--input=tmp/tmp_txt --model_prefix=' + output_dir + ' --add_dummy_prefix=0 --max_sentencepiece_length=512 --model_type=bpe --mining_sentence_size=5000000 --input_sentence_size=10000000 --vocab_size=50000')
OSError: Not found: unknown field name "mining_sentence_size" in TrainerSpec.

**Comment by nbutyrate** [comment]
I have solved this issue, please feel free to close this

**Comment by jzl0166** [comment]
How could you solve this problem?
